CREATE TABLE types (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX ON types (name);

CREATE TABLE owners (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT,
    address    TEXT,
    city       TEXT,
    telephone  TEXT
);
CREATE INDEX ON owners (last_name);

CREATE TABLE pets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT,
    birth_date DATE,
    type_id    INT NOT NULL REFERENCES types (id),
    owner_id   INT REFERENCES owners (id)
);
CREATE INDEX ON pets (name);
CREATE INDEX ON pets (owner_id);

CREATE TABLE visits (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INT REFERENCES pets (id),
    visit_date  DATE,
    description TEXT
);
CREATE INDEX ON visits (pet_id);
