CREATE TABLE vets (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT,
    last_name  TEXT
);
CREATE INDEX ON vets (last_name);

CREATE TABLE specialties (
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);
CREATE INDEX ON specialties (name);

CREATE TABLE vet_specialties (
    vet_id       INT NOT NULL REFERENCES vets (id),
    specialty_id INT NOT NULL REFERENCES specialties (id),
    UNIQUE (vet_id, specialty_id)
);

CREATE TABLE users (
    username VARCHAR(20) NOT NULL,
    password VARCHAR(60) NOT NULL,
    enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_users PRIMARY KEY (username)
);

CREATE TABLE roles (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    role     VARCHAR(20) NOT NULL,
    FOREIGN KEY (username) REFERENCES users (username),
    CONSTRAINT uni_username_role UNIQUE (role, username)
);
