-- Vets publish a recurring weekly availability; SlotGenerator expands it into bookable slots,
-- and a visit may claim exactly one of them. Legacy visits keep vet_id and time_slot_id NULL.

CREATE TABLE vet_schedules (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id       INT         NOT NULL REFERENCES vets (id),
    day_of_week  VARCHAR(10) NOT NULL,
    start_time   TIME        NOT NULL,
    end_time     TIME        NOT NULL,
    slot_minutes INT         NOT NULL,
    UNIQUE (vet_id, day_of_week)
);

CREATE TABLE time_slots (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vet_id     INT  NOT NULL REFERENCES vets (id),
    slot_date  DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time   TIME NOT NULL,
    UNIQUE (vet_id, slot_date, start_time)
);
CREATE INDEX ON time_slots (slot_date);

ALTER TABLE visits ADD COLUMN vet_id INT REFERENCES vets (id);
ALTER TABLE visits ADD COLUMN time_slot_id INT REFERENCES time_slots (id);

-- One visit per slot: the last line of defence against a double booking that slipped
-- past the free-slot check under concurrency.
ALTER TABLE visits ADD CONSTRAINT visits_time_slot_uq UNIQUE (time_slot_id);
CREATE INDEX ON visits (vet_id);

-- Every vet holds weekday morning consultations in 30-minute slots.
INSERT INTO vet_schedules (vet_id, day_of_week, start_time, end_time, slot_minutes)
SELECT v.id, d.day, TIME '09:00', TIME '13:00', 30
FROM vets v
         CROSS JOIN (VALUES ('MONDAY'), ('TUESDAY'), ('WEDNESDAY'), ('THURSDAY'), ('FRIDAY')) AS d(day);
