@startuml

title Logical Architecture
caption All lines are ArchUnit-tested to be reflected in code.

[Model] <<..model>>
[Repository] <<..repository>>
[DTO] <<..rest.dto>>
[REST Error] <<..rest.error>>
[Mapper] <<..mapper>>
[REST] <<..rest>>
[Invoice] <<..invoice>>
[Security] <<..security>>
[Ghost] <<..ghost>>

[Repository] --> [Model]
[Mapper] --> [Model]
[Mapper] --> [DTO]
[REST] --> [Model]
[REST] --> [Repository]
[REST] --> [Mapper]
[REST] --> [DTO]

@enduml
