sonar.projectKey=victorrentea_petclinic
sonar.organization=victorrentea
sonar.host.url=https://sonarcloud.io

sonar.sources=petclinic-backend/src/main,petclinic-frontend/src
sonar.tests=petclinic-backend/src/test,petclinic-frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java,**/*IT.java
sonar.exclusions=**/generated/**,**/generated-sources/**,**/target/**,**/node_modules/**,**/dist/**,petclinic-frontend/src/app/generated/**

sonar.java.source=21
sonar.java.binaries=petclinic-backend/target/classes
sonar.java.test.binaries=petclinic-backend/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=petclinic-backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=petclinic-frontend/coverage/lcov.info

sonar.typescript.tsconfigPath=petclinic-frontend/tsconfig.json
