sonar.projectKey=victorrentea_petclinic
sonar.organization=victorrentea
sonar.host.url=https://sonarcloud.io

sonar.sources=petclinic-frontend/src
sonar.tests=petclinic-frontend/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/generated/**,**/node_modules/**,**/dist/**,petclinic-frontend/src/app/generated/**

sonar.javascript.lcov.reportPaths=petclinic-frontend/coverage/lcov.info

sonar.coverage.exclusions=petclinic-frontend/src/otel.ts

sonar.typescript.tsconfigPath=petclinic-frontend/tsconfig.json
