"""Throwaway DB with ~50k owners + V4, then EXPLAIN ANALYZE of every grid page/count query."""
import re, sys
import psycopg

V4 = open(sys.argv[1]).read()
DB = 'owners_explain_tmp'
SERVER = 'host=localhost port=5432 user=postgres'
admin = psycopg.connect(f'{SERVER} dbname=postgres', autocommit=True)
admin.execute(f'DROP DATABASE IF EXISTS {DB}')
admin.execute(f'CREATE DATABASE {DB}')

# 50k owners: 400 surnames (some Romanian/Polish), 300 first names, 600 cities skewed to a few
GENERATE_OWNERS = """
WITH s AS (
    SELECT array_agg(x) a FROM (
        SELECT unnest(ARRAY['Popescu', 'Ionescu', 'Șerban', 'Țepeș', 'Ștefănescu',
            'Śliwiński', 'Łukasiewicz', 'Potter', 'Smith', 'Jones', 'García Márquez',
            'Müller', 'Dumitrescu', 'Îndrieș'])
        UNION ALL SELECT 'Surname' || g FROM generate_series(1, 386) g) t(x)),
f AS (SELECT array_agg('First' || g) a FROM generate_series(1, 300) g),
k AS (
    SELECT array_agg(x) a FROM (
        SELECT unnest(ARRAY['London', 'București', 'Brașov', 'Kraków', 'Vienna'])
        UNION ALL SELECT 'City' || g FROM generate_series(1, 595) g) t(x))
INSERT INTO owners (first_name, last_name, address, city, telephone)
SELECT f.a[1 + (g * 7919) % 300], s.a[1 + (g * 104729) % 400], g || ' Some Street',
    CASE WHEN g % 5 = 0 THEN k.a[1 + g % 5] ELSE k.a[1 + (g * 31) % 600] END, '0700000000'
FROM generate_series(1::bigint, 50000) g, s, f, k"""

ORDERS = {
    'name asc':  'last_name, first_name, id',
    'name desc': 'last_name DESC, first_name DESC, id DESC',
    'city asc':  'city, last_name, first_name, id',
    'city desc': 'city DESC, last_name, first_name, id',
}
FILTERS = {"no filter (lastName='')": '%', "lastName='Pot'": 'Pot%'}
PAGE_SQL = ("SELECT * FROM owners WHERE last_name LIKE $1 ESCAPE '\\' "
            "ORDER BY {order} OFFSET $2 LIMIT $3")
COUNT_SQL = "SELECT count(id) FROM owners WHERE last_name LIKE $1 ESCAPE '\\'"
GENERIC = 'generic plan (what a server-prepared statement may switch to)'


def plan(c, sql, params, generic=False):
    c.execute('SET plan_cache_mode = ' + ('force_generic_plan' if generic else 'auto'))
    c.execute('DEALLOCATE ALL')
    c.execute(f'PREPARE q AS {sql}')
    explain = 'EXPLAIN (ANALYZE, COSTS OFF, TIMING OFF, SUMMARY ON) '
    rows = c.execute(explain + f"EXECUTE q({', '.join(params)})").fetchall()
    lines = [r[0] for r in rows]
    nodes = [l.strip() for l in lines if re.search(r'(Scan|Sort|Limit|Aggregate|Filter|Cond)', l)]
    ms = next(l for l in lines if l.startswith('Execution Time')).split(':')[1].strip()
    return nodes, ms


def block(title, nodes):
    return f'### {title}\n```\n' + '\n'.join(nodes) + '\n```\n'


out = []
try:
    with psycopg.connect(f'{SERVER} dbname={DB}', autocommit=True, prepare_threshold=None) as c:
        c.execute("""CREATE TABLE owners (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name TEXT, last_name TEXT, address TEXT, city TEXT, telephone TEXT)""")
        c.execute(V4)
        c.execute(GENERATE_OWNERS)
        c.execute('ANALYZE owners')
        total = c.execute('SELECT count(*) FROM owners').fetchone()[0]
        out.append(f'Generated {total} owners.\n')

        for fname, pattern in FILTERS.items():
            for generic in (False, True):
                mode = GENERIC if generic else 'custom plan'
                nodes, ms = plan(c, COUNT_SQL, [f"'{pattern}'"], generic)
                out.append(block(f'count, {fname}, {mode}: {ms}', nodes))
                for oname, order in ORDERS.items():
                    for offset in (0, 49990):
                        if pattern != '%' and offset:
                            continue
                        params = [f"'{pattern}'", str(offset), '10']
                        nodes, ms = plan(c, PAGE_SQL.format(order=order), params, generic)
                        title = f'page, {fname}, sort {oname}, offset {offset}, {mode}: {ms}'
                        out.append(block(title, nodes))
finally:
    admin.execute(f'DROP DATABASE IF EXISTS {DB} WITH (FORCE)')
print('\n'.join(out))
