@startuml
hide footbox
title Add a visit to an existing pet from the owner detail page
footer @generate_sequence Scenario in a .feature test
participant Browser
participant Backend
participant DB
== Add a visit to an existing pet from the owner detail page #1 ==
Browser -> Backend: GET /api/owners/{ownerId}
activate Backend
Backend -> Backend: OwnerRepository.findById
activate Backend
Backend -> DB: petclinic
activate DB
deactivate DB
Backend -> Backend: Session.find victor.training.petclinic.domain.Owner
activate Backend
Backend -> DB: SELECT petclinic.owners
activate DB
deactivate DB
deactivate Backend
Backend -> Backend: Transaction.commit
activate Backend
deactivate Backend
deactivate Backend
Backend -> DB: SELECT petclinic
activate DB
deactivate DB
Backend -> DB: SELECT petclinic.visits
activate DB
deactivate DB
Backend --> Browser: 200
deactivate Backend
== Add a visit to an existing pet from the owner detail page #2 ==
Browser -> Backend: GET /api/owners/{ownerId}
activate Backend
Backend -> Backend: OwnerRepository.findById
activate Backend
Backend -> Backend: Session.find victor.training.petclinic.domain.Owner
activate Backend
Backend -> DB: SELECT petclinic.owners
activate DB
deactivate DB
deactivate Backend
Backend -> Backend: Transaction.commit
activate Backend
deactivate Backend
deactivate Backend
Backend -> DB: SELECT petclinic
activate DB
deactivate DB
Backend -> DB: SELECT petclinic.visits
activate DB
deactivate DB
Backend --> Browser: 200
deactivate Backend
== Add a visit to an existing pet from the owner detail page #3 ==
Browser -> Backend: GET /api/pets/{petId}
activate Backend
Backend -> Backend: PetRepository.findById
activate Backend
Backend -> Backend: Session.find victor.training.petclinic.domain.Pet
activate Backend
Backend -> DB: SELECT petclinic
activate DB
deactivate DB
deactivate Backend
Backend -> Backend: Transaction.commit
activate Backend
deactivate Backend
deactivate Backend
Backend -> DB: SELECT petclinic.visits
activate DB
deactivate DB
Backend --> Browser: 200
deactivate Backend
== Add a visit to an existing pet from the owner detail page #4 ==
Browser -> Backend: POST /api/owners/{ownerId}/pets/{petId}/visits
activate Backend
Backend -> Backend: VisitRepository.save
activate Backend
Backend -> Backend: Session.persist victor.training.petclinic.domain.Visit
activate Backend
Backend -> DB: INSERT petclinic.visits
activate DB
deactivate DB
deactivate Backend
Backend -> Backend: Transaction.commit
activate Backend
deactivate Backend
deactivate Backend
Backend --> Browser: 201
deactivate Backend
@enduml
