#!/usr/bin/env bash
# Red-annotated delta for *every* PlantUML diagram this branch touched.
#
# `architecture-diff.sh` answers "what did this branch do to the three structural
# diagrams?" — an explicit, curated list. This script answers the wider review
# question: take every .puml that differs from the base (committed, modified or
# brand new in the work tree), and render each one as a delta where additions are
# red and removals are red + struck through.
#
# Two diagram families need two algorithms, and the script dispatches between them:
#
#   structural (class / ER / package)  -> puml_diff.py      set semantics
#   sequence   (participants + arrows) -> seq_puml_diff.py  ordered-script semantics
#
# Output (default .human-review/assets/diagrams/):
#   <name>.diff.puml   the merged delta
#   <name>.diff.svg    rendered, when plantuml is on PATH
#   MANIFEST.tsv       name / source path / kind / status / diff.puml / svg
#
# Usage:
#   scripts/puml-diff.sh [base-ref] [out-dir]
#   scripts/puml-diff.sh origin/main .human-review/assets/diagrams
#
# Exit codes: 0 = done (zero changed diagrams is a normal, quiet 0), 2 = bad usage.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
cd "$ROOT"

BASE_REF="${1:-origin/main}"
OUT_DIR="${2:-.human-review/assets/diagrams}"

STRUCT_DIFF="$ROOT/petclinic-backend/docs/scripts/puml-diff/puml_diff.py"
SEQ_DIFF="$ROOT/petclinic-backend/docs/scripts/puml-diff/seq_puml_diff.py"

for tool in "$STRUCT_DIFF" "$SEQ_DIFF"; do
  [ -f "$tool" ] || { echo "[puml-diff] missing $tool" >&2; exit 2; }
done

if ! git rev-parse --verify --quiet "$BASE_REF^{commit}" >/dev/null; then
  echo "[puml-diff] unknown base ref '$BASE_REF'" >&2
  exit 2
fi

# Against the merge-base, not the base tip: commits that landed on the base after
# this branch started are not this branch's changes.
MERGE_BASE="$(git merge-base "$BASE_REF" HEAD)"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# The work tree, not HEAD: a sequence diagram regenerated by the test run this
# review is about is still uncommitted, and it is exactly what the reviewer needs
# to see. Untracked .puml files count as additions.
# (a plain read loop rather than `mapfile`: macOS ships bash 3.2)
CHANGED=()
while IFS= read -r line; do
  [ -n "$line" ] && CHANGED+=("$line")
done < <(
  {
    git diff --name-only "$MERGE_BASE" -- '*.puml'
    git ls-files --others --exclude-standard -- '*.puml'
  } | sort -u
)

MANIFEST="$OUT_DIR/MANIFEST.tsv"
printf 'name\tsource\tkind\tstatus\tdiff_puml\tsvg\n' > "$MANIFEST"

# A sequence diagram is the one that declares lifelines and sends messages along
# them; everything else in this repo is a structural snapshot.
classify() {
  if grep -qiE '^\s*(participant|actor|boundary|control|entity[[:space:]]+"?[A-Za-z]+"?\s*$)' "$1" \
    && grep -qE '^\s*[^-<>:]+\s*(-{1,2}>>?|<<?-{1,2})\s*[^-<>:]+\s*:' "$1"; then
    echo sequence
  else
    echo structural
  fi
}

count=0
for rel in "${CHANGED[@]}"; do
  [ -n "$rel" ] || continue
  name="$(basename "${rel%.puml}")"

  old="$TMP/$name.base.puml"
  status=modified
  if ! git show "$MERGE_BASE:$rel" >"$old" 2>/dev/null; then
    : >"$old"
    status=added
  fi

  new="$ROOT/$rel"
  if [ ! -f "$new" ]; then
    new="$TMP/$name.empty.puml"
    : >"$new"
    status=deleted
  fi

  if cmp -s "$old" "$new"; then
    continue
  fi

  # Classify on whichever side actually has content, so a brand-new sequence
  # diagram is not misread as structural just because its base side is empty.
  probe="$new"; [ -s "$probe" ] || probe="$old"
  kind="$(classify "$probe")"

  diff_puml="$OUT_DIR/$name.diff.puml"
  if [ "$status" = added ]; then
    # Nothing to compare against, so nothing to mark: reddening every line of a diagram
    # that simply did not exist before says "all of this changed" when what happened is
    # "this is new". The manifest already carries the status.
    cp "$new" "$diff_puml"
  elif [ "$kind" = sequence ]; then
    python3 "$SEQ_DIFF" "$old" "$new" --out "$diff_puml"
  else
    python3 "$STRUCT_DIFF" "$old" "$new" --out "$diff_puml"
  fi

  svg=""
  if command -v plantuml >/dev/null 2>&1; then
    plantuml -tsvg "$diff_puml" >/dev/null 2>&1 || true
    [ -f "${diff_puml%.puml}.svg" ] && svg="$(basename "${diff_puml%.puml}.svg")"
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$name" "$rel" "$kind" "$status" "$(basename "$diff_puml")" "$svg" >> "$MANIFEST"
  echo "[puml-diff] $rel ($kind, $status) -> $diff_puml" >&2
  count=$((count + 1))
done

if [ "$count" -eq 0 ]; then
  echo "[puml-diff] no diagram changed vs $BASE_REF (merge-base $(git rev-parse --short "$MERGE_BASE"))" >&2
else
  command -v plantuml >/dev/null 2>&1 || \
    echo "[puml-diff] plantuml not on PATH — .diff.puml written, but nothing rendered" >&2
  echo "[puml-diff] $count diagram(s) -> $OUT_DIR (see MANIFEST.tsv)" >&2
fi
