#!/usr/bin/env python3
"""Build the static index.html for a PR's architecture-delta gallery.

Reads the *.diff.svg rendered next to the *.diff.puml in the given directory and
emits a self-contained page — no external CSS, fonts, or scripts, because the
page has to keep working when it is the only record of what a PR proposed.

Context comes from the environment (PR_NUMBER, PR_TITLE, PR_BRANCH, PR_BASE,
REPO) so the workflow can pass it without quoting a title through a shell.

Usage:
    build_pr_gallery.py pr-diff
"""
from __future__ import annotations

import html
import os
import sys
from pathlib import Path

# Diagram file stem → the name a reviewer would recognise.
TITLES = {
    "DomainModel": "Domain model",
    "DB": "Database schema (ERD)",
    "packages": "Logical architecture (packages)",
}

STYLE = """
:root { color-scheme: light dark; --fg:#1a1a1a; --muted:#5a5a5a; --bg:#fff;
        --card:#fafafa; --line:#e3e3e3; --accent:#c0392b; }
@media (prefers-color-scheme: dark) {
  :root { --fg:#e8e8e8; --muted:#a0a0a0; --bg:#141414; --card:#1d1d1d;
          --line:#333; --accent:#ff6b5a; }
}
* { box-sizing: border-box; }
body { margin:0; padding:2rem 1.25rem 4rem; background:var(--bg); color:var(--fg);
       font:16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
main { max-width: 60rem; margin: 0 auto; }
h1 { font-size:1.5rem; margin:0 0 .25rem; }
h2 { font-size:1.1rem; margin:0 0 .75rem; font-weight:600; }
.sub { color:var(--muted); font-size:.9rem; margin:0 0 2rem; }
.sub a { color:inherit; }
.legend { display:inline-block; border-left:3px solid var(--accent); padding:.4rem .75rem;
          background:var(--card); font-size:.875rem; margin-bottom:2rem; }
figure { margin:0 0 2.5rem; border:1px solid var(--line); border-radius:8px;
         background:var(--card); overflow:hidden; }
figcaption { padding:.75rem 1rem; border-bottom:1px solid var(--line); }
figcaption code { color:var(--muted); font-size:.8rem; }
.frame { overflow-x:auto; padding:1.25rem; background:#fff; }
@media (prefers-color-scheme: dark) { .frame { background:#f4f4f4; } }
.frame img { display:block; max-width:100%; height:auto; margin:0 auto; }
footer { color:var(--muted); font-size:.825rem; border-top:1px solid var(--line);
         padding-top:1rem; }
"""


def build(directory: Path) -> str:
    pr = os.environ.get("PR_NUMBER", "?")
    title = os.environ.get("PR_TITLE", "")
    branch = os.environ.get("PR_BRANCH", "?")
    base = os.environ.get("PR_BASE", "main")
    repo = os.environ.get("REPO", "")

    svgs = sorted(directory.glob("*.diff.svg"))
    parts = [
        "<!doctype html>", '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>Architecture delta — PR #{html.escape(pr)}</title>",
        f"<style>{STYLE}</style></head><body><main>",
        f"<h1>Architecture delta — PR #{html.escape(pr)}</h1>",
    ]

    pr_link = f"https://github.com/{repo}/pull/{pr}" if repo else "#"
    parts.append(
        f'<p class="sub">{html.escape(title)}<br>'
        f'<code>{html.escape(branch)}</code> → <code>{html.escape(base)}</code> · '
        f'<a href="{pr_link}">view the pull request</a></p>'
    )

    if not svgs:
        parts.append("<p>No architecture diagram changed on this branch.</p>")
    else:
        parts.append('<p class="legend"><strong>Red</strong> = added · '
                     "<strong>Red struck-through</strong> = removed. "
                     "Each image is the <em>delta</em>, not the snapshot.</p>")
        for svg in svgs:
            stem = svg.name[: -len(".diff.svg")]
            parts += [
                "<figure>",
                f"<figcaption><h2>{html.escape(TITLES.get(stem, stem))}</h2>"
                f"<code>{html.escape(stem)}.puml</code></figcaption>",
                f'<div class="frame"><img src="{html.escape(svg.name)}" '
                f'alt="{html.escape(TITLES.get(stem, stem))} delta"></div>',
                "</figure>",
            ]

    parts.append(
        "<footer>Generated by <code>scripts/architecture-diff.sh</code>. "
        "This page is a review artifact — it is deleted when the pull request closes, "
        "and never lands on <code>main</code>.</footer>"
    )
    parts.append("</main></body></html>")
    return "\n".join(parts)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    directory = Path(argv[0] if argv else "pr-diff")
    if not directory.is_dir():
        print(f"[gallery] {directory} is not a directory", file=sys.stderr)
        return 2
    out = directory / "index.html"
    out.write_text(build(directory), encoding="utf-8")
    print(f"[gallery] wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
