#!/usr/bin/env python3
"""Generate (or check) the list of Maven dependencies declared WITHOUT a <version>.

Such dependencies inherit their version from a parent POM / BOM (e.g.
spring-boot-starter-parent). That makes the *set* of version-managed dependencies
invisible — it is spread across several poms and the version is never shown. This
script collapses that surface into one committed, reviewable file
(``petclinic-backend/pom-libs.txt``) so the elders can keep an eye on it via CODEOWNERS:
adding or removing a versionless dependency shows up as a one-line diff.

Usage:
    list-unversioned-deps.py            # regenerate petclinic-backend/pom-libs.txt
    list-unversioned-deps.py --check    # exit 1 (with a diff) if the file is stale

Stdlib only — no Maven, no network. Safe to run in a pre-commit hook and in CI.
"""

from __future__ import annotations

import difflib
import os
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = REPO_ROOT / "petclinic-backend" / "pom-libs.txt"

# Directories that never contain source poms we care about (build output, deps,
# and the throw-away git worktrees under .claude/worktrees).
PRUNE_DIRS = {"target", "node_modules", ".git", ".claude", ".worktrees"}

# Maven 4.0.0 POMs use this default namespace on every element.
POM_NS = "http://maven.apache.org/POM/4.0.0"

HEADER = """\
# Dependencies declared WITHOUT an explicit <version> — their version is inherited
# from a parent POM / BOM (e.g. spring-boot-starter-parent). This file is the
# version-managed dependency surface collapsed into one place.
#
# Generated by scripts/list-unversioned-deps.py — DO NOT EDIT BY HAND.
# Regenerate with: python3 scripts/list-unversioned-deps.py
# Protected by CODEOWNERS so the elders review any change to this surface.
"""


def _strip_ns(tag: str) -> str:
    """Return an element's local name, dropping any ``{namespace}`` prefix."""
    return tag.rsplit("}", 1)[-1]


def find_module_poms(root: Path) -> list[Path]:
    """Walk ``root`` for pom.xml files, pruning build/dependency/worktree dirs."""
    poms: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in PRUNE_DIRS]
        if "pom.xml" in filenames:
            poms.append(Path(dirpath) / "pom.xml")
    return sorted(poms)


def _find(parent: ET.Element, local_name: str) -> ET.Element | None:
    """First direct child of ``parent`` whose local name is ``local_name``."""
    for child in parent:
        if _strip_ns(child.tag) == local_name:
            return child
    return None


def unversioned_deps(pom: Path) -> list[str]:
    """Return ``groupId:artifactId`` for each <dependency> in <project>/<dependencies>
    that has no <version> child. <dependencyManagement> and plugin deps are excluded."""
    root = ET.parse(pom).getroot()
    deps_el = _find(root, "dependencies")  # only the project-level <dependencies>
    if deps_el is None:
        return []

    result: list[str] = []
    for dep in deps_el:
        if _strip_ns(dep.tag) != "dependency":
            continue
        version = _find(dep, "version")
        if version is not None and (version.text or "").strip():
            continue  # has an explicit version — not part of the managed surface
        group = _find(dep, "groupId")
        artifact = _find(dep, "artifactId")
        if group is None or artifact is None:
            continue
        result.append(f"{(group.text or '').strip()}:{(artifact.text or '').strip()}")
    return sorted(set(result))


def render() -> str:
    """Build the full file contents from the current poms (deterministic)."""
    lines: list[str] = []
    lines.extend(HEADER.rstrip("\n").split("\n"))
    for pom in find_module_poms(REPO_ROOT):
        module = pom.parent.relative_to(REPO_ROOT).as_posix() or "."
        deps = unversioned_deps(pom)
        if not deps:
            continue
        lines.append("")  # one blank line before each module block
        lines.append(f"{module}:")
        lines.extend(f"  {dep}" for dep in deps)
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    generated = render()

    if check:
        current = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else ""
        if current == generated:
            print(f"[unversioned-deps] ✓ {OUTPUT_FILE.name} is up to date.")
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=f"{OUTPUT_FILE.name} (committed)",
            tofile=f"{OUTPUT_FILE.name} (regenerated)",
        )
        sys.stdout.writelines(diff)
        print(f"\n[unversioned-deps] ❌ {OUTPUT_FILE.name} is stale — regenerate it.")
        return 1

    OUTPUT_FILE.write_text(generated)
    print(f"[unversioned-deps] wrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
