// A REST hop's span name is its route — `GET /api/pets/{petId}`. That says where the
// call went, not what it was for, and a reviewer reading a sequence diagram is asking
// the second question. The API already answers it: every operation in openapi.yaml
// carries a name. So the arrow gets both grains, the operation above its route.
//
// Read with a scanner rather than a YAML library. The file is generated by springdoc,
// so its shape is a fixed two-space ladder — `paths:` → route → verb → key — and the
// three levels this needs are not worth a whole YAML dependency in the test module.

import * as fs from 'fs';
import * as path from 'path';

/** `GET /api/pets/{petId}` → the API's name for that operation. */
export type OperationNames = Map<string, string>;

const VERBS = ['get', 'put', 'post', 'delete', 'patch', 'head', 'options', 'trace'];

const ROUTE_RE = /^ {2}(\/\S*):\s*$/;
const VERB_RE = new RegExp(`^ {4}(${VERBS.join('|')}):\\s*$`);
const NAMED_RE = /^ {6}(operationId|summary):\s*(.*?)\s*$/;

/** YAML quoting, as springdoc emits it — plain, or wrapped in one kind of quote. */
function unquote(value: string): string {
  const m = /^(['"])([\s\S]*)\1$/.exec(value);
  return m ? m[2] : value;
}

/**
 * Every operation in the document, keyed `VERB /route`.
 *
 * `summary` wins over `operationId` where the API author wrote one: it is prose meant
 * for a human, which is what an arrow label is. Only a minority of operations have one,
 * so `operationId` is the fallback that makes the lookup total rather than patchy.
 */
export function parseOperations(yaml: string): OperationNames {
  const operations: OperationNames = new Map();
  let route: string | undefined;
  let verb: string | undefined;
  let inPaths = false;

  for (const line of yaml.split('\n')) {
    if (/^\S/.test(line)) {
      // any top-level key closes the paths block — `components:` follows it
      inPaths = line.startsWith('paths:');
      route = verb = undefined;
      continue;
    }
    if (!inPaths) continue;

    const routeMatch = ROUTE_RE.exec(line);
    if (routeMatch) {
      route = routeMatch[1];
      verb = undefined;
      continue;
    }
    const verbMatch = VERB_RE.exec(line);
    if (verbMatch) {
      verb = verbMatch[1];
      continue;
    }
    const named = NAMED_RE.exec(line);
    if (!named || !route || !verb) continue;

    const key = `${verb.toUpperCase()} ${route}`;
    const value = unquote(named[2]);
    if (!value) continue;
    // summary overwrites an operationId already stored for this key; operationId must
    // not overwrite a summary, and the two can arrive in either order
    if (named[1] === 'summary' || !operations.has(key)) operations.set(key, value);
  }
  return operations;
}

/** The repo's own contract — three levels up from `petclinic-test/src/genseq`. */
export const DEFAULT_SPEC = path.resolve(__dirname, '..', '..', '..', 'openapi.yaml');

let cached: OperationNames | undefined;

/**
 * The operations of the repo's openapi.yaml, read once.
 *
 * A missing or unreadable spec is not a failure: the arrow simply keeps its route and
 * nothing else about the diagram changes. Generating a picture of a trace must not
 * depend on the contract file being where this expects it.
 */
export function defaultOperations(): OperationNames {
  if (!cached) {
    try {
      cached = parseOperations(fs.readFileSync(DEFAULT_SPEC, 'utf-8'));
    } catch {
      cached = new Map();
    }
  }
  return cached;
}

const ROUTE_SPAN_RE = new RegExp(`^(${VERBS.join('|')})\\s+(/\\S*)$`, 'i');

/** The operation name for a span called `GET /api/pets/{petId}`, if the spec names one. */
export function operationNameOf(spanName: string, operations: OperationNames): string | undefined {
  const m = ROUTE_SPAN_RE.exec(spanName.trim());
  if (!m) return undefined;
  return operations.get(`${m[1].toUpperCase()} ${m[2]}`);
}
