@startuml
title <size:24>Component View: PetClinic - Backend</size>\n<size:24>Repository layer dependencies</size>

set separator none
left to right direction
skinparam ranksep 20
skinparam nodesep 5
hide stereotype

<style>
  root {
    BackgroundColor: #ffffff;
    FontColor: #444444;
  }
  // Element
  .Element-RWxlbWVudA== {
    BackgroundColor: #ffffff;
    LineColor: #444444;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #444444;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
    MaximumWidth: 450;
  }
  // Relationship
  .Relationship-UmVsYXRpb25zaGlw {
    LineThickness: 2;
    LineStyle: 10-10;
    LineColor: #444444;
    FontColor: #444444;
    FontSize: 24;
  }
  // Backend
  .Boundary-QmFja2VuZA== {
    BackgroundColor: #ffffff;
    LineColor: #444444;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #444444;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
  // PetClinic
  .Boundary-UGV0Q2xpbmlj {
    BackgroundColor: #ffffff;
    LineColor: #444444;
    LineStyle: 0;
    LineThickness: 2;
    FontColor: #444444;
    FontSize: 24;
    HorizontalAlignment: center;
    Shadowing: 0;
  }
</style>

rectangle "PetClinic\n<size:16>[Software System]</size>" <<Boundary-UGV0Q2xpbmlj>> {
  rectangle "Backend\n<size:16>[Container: Java / Spring Boot]</size>" <<Boundary-QmFja2VuZA==>> {
    rectangle "==REST Layer\n<size:16>[Component: Spring MVC]</size>\n\nHTTP endpoints, DTOs, error handlers" <<Element-RWxlbWVudA==>> as PetClinic.Backend.RESTLayer
    rectangle "==Domain Model\n<size:16>[Component: JPA]</size>\n\nJPA entities" <<Element-RWxlbWVudA==>> as PetClinic.Backend.DomainModel
    rectangle "==Repository Layer\n<size:16>[Component: Spring Data]</size>\n\nSpring Data JPA repositories" <<Element-RWxlbWVudA==>> as PetClinic.Backend.RepositoryLayer
  }

}

PetClinic.Backend.RepositoryLayer --> PetClinic.Backend.DomainModel <<Relationship-UmVsYXRpb25zaGlw>> : ""
PetClinic.Backend.RESTLayer --> PetClinic.Backend.DomainModel <<Relationship-UmVsYXRpb25zaGlw>> : ""
PetClinic.Backend.RESTLayer --> PetClinic.Backend.RepositoryLayer <<Relationship-UmVsYXRpb25zaGlw>> : ""

@enduml