import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Creates the core owners and pets schema.
 * Table and column names use snake_case.
 */
export class CoreOwnersPets1700000000001 implements MigrationInterface {
  name = 'CoreOwnersPets1700000000001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE types (
          id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT
      )
    `);
    await queryRunner.query(`CREATE INDEX ON types (name)`);

    await queryRunner.query(`
      CREATE TABLE owners (
          id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          first_name TEXT,
          last_name  TEXT,
          address    TEXT,
          city       TEXT,
          telephone  TEXT
      )
    `);
    await queryRunner.query(`CREATE INDEX ON owners (last_name)`);

    await queryRunner.query(`
      CREATE TABLE pets (
          id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name       TEXT,
          birth_date DATE,
          type_id    INT NOT NULL REFERENCES types (id),
          owner_id   INT REFERENCES owners (id)
      )
    `);
    await queryRunner.query(`CREATE INDEX ON pets (name)`);
    await queryRunner.query(`CREATE INDEX ON pets (owner_id)`);

    await queryRunner.query(`
      CREATE TABLE visits (
          id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          pet_id      INT REFERENCES pets (id),
          visit_date  DATE,
          description TEXT
      )
    `);
    await queryRunner.query(`CREATE INDEX ON visits (pet_id)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS visits`);
    await queryRunner.query(`DROP TABLE IF EXISTS pets`);
    await queryRunner.query(`DROP TABLE IF EXISTS owners`);
    await queryRunner.query(`DROP TABLE IF EXISTS types`);
  }
}
