import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Adds the vets, specialties, users and roles schema.
 * Table and column names use snake_case.
 */
export class AddVetsAndSecurity1700000000002 implements MigrationInterface {
  name = 'AddVetsAndSecurity1700000000002';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE vets (
          id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          first_name TEXT,
          last_name  TEXT
      )
    `);
    await queryRunner.query(`CREATE INDEX ON vets (last_name)`);

    await queryRunner.query(`
      CREATE TABLE specialties (
          id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT
      )
    `);
    await queryRunner.query(`CREATE INDEX ON specialties (name)`);

    await queryRunner.query(`
      CREATE TABLE vet_specialties (
          vet_id       INT NOT NULL REFERENCES vets (id),
          specialty_id INT NOT NULL REFERENCES specialties (id),
          UNIQUE (vet_id, specialty_id)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE users (
          username VARCHAR(20) NOT NULL,
          password VARCHAR(60) NOT NULL,
          enabled  BOOLEAN     NOT NULL DEFAULT TRUE,
          CONSTRAINT pk_users PRIMARY KEY (username)
      )
    `);

    await queryRunner.query(`
      CREATE TABLE roles (
          id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username VARCHAR(20) NOT NULL,
          role     VARCHAR(20) NOT NULL,
          FOREIGN KEY (username) REFERENCES users (username),
          CONSTRAINT uni_username_role UNIQUE (role, username)
      )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS roles`);
    await queryRunner.query(`DROP TABLE IF EXISTS users`);
    await queryRunner.query(`DROP TABLE IF EXISTS vet_specialties`);
    await queryRunner.query(`DROP TABLE IF EXISTS specialties`);
    await queryRunner.query(`DROP TABLE IF EXISTS vets`);
  }
}
